### ISSUE TITLE
Add Support for Double Bar Headers - Confluence Wiki Markup

### ISSUE THREAD

**Issue by terriann** [donatj/CsvToMarkdownTable#5]
Discovered your sample looking to convert some CSVs to a table for use in JIRA cloud comments and descriptions.  The flavor of markdown used there has a different table syntax and uses two bar lines instead of a separator bar row to indicate the `<th>` cells.

Documentation reference: https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=tables

## Example

**From**

    key,sandwich,points,notes
    1,Chicken Salad,48,With just enough seasoning
    2,Turkey & Bacon,263,Healthy but with bacon
    3,Bologna and cheese,1,Classic Favorite

**To**

    || key || sandwich           || points || notes                      || 
    |  1    | Chicken Salad       | 48      | With just enough seasoning  | 
    |  2    | Turkey & Bacon      | 263     | Healthy but with bacon      | 
    |  3    | Bologna and cheese  | 1       | Classic Favorite            | 

**Which displays as** (in JIRA Cloud)
![screenshot](https://user-images.githubusercontent.com/316632/27164285-348e955e-515a-11e7-9e7f-a4bd8ad23cab.png)

In case you're open to this feature I will submit a pull request with tests that I worked on.

Happy to make updates based on your feedback. First time contributor here (new to Mocha and TypeScript too) so thanks in advance for your patience!

**Comment by donatj** [comment]
I truly appreciate the pull request, and the work you've put into this, but I think this might be outside of the scope of what my library is intended to be. 

[Confluence Wiki Markup](https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html) is not Markdown.

There is an existing although somewhat aged `csv2confluence` fork of my library that lives here: https://github.com/jriquelme/csv2confluence 

You could poke them to update it, but I don't know if that would be fruitful. 

Otherwise you could maintain your own confluence fork of this.  If you do choose to fork I'd happily link to you from my README for people looking for Confluence tables as there does appear to be interest.

**Comment by terriann** [comment]
Thanks so much for your prompt response @donat. I didn't realize that style was markup and that it wasn't just another flavor of markdown. I will keep my fork because it's something I'll want to use and your project is a GREAT base for tinkering.

I've renamed my fork to terriann/CsvToPlainTextTable and updated some information. Cheers!
